import { prisma } from '../config/database.js'; import { conversations } from './conversation.service.js';
const include={sender:{select:{id:true,displayName:true,avatar:true,status:true,lastSeen:true}},receiver:{select:{id:true,displayName:true,avatar:true,status:true,lastSeen:true}},attachments:true,reactions:true,readReceipts:true} as const;
export const messages={
 async create(senderId:string,p:{conversationId:string;receiverId:string;type?:'TEXT'|'EMOJI'|'STICKER'|'GIF'|'IMAGE'|'FILE';content:string;replyToId?:string;attachments?:{url:string;fileName:string;mimeType:string;fileSize:number}[]}){await conversations.assertMember(p.conversationId,senderId);await conversations.assertMember(p.conversationId,p.receiverId);return prisma.$transaction(async tx=>{const message=await tx.message.create({data:{conversationId:p.conversationId,senderId,receiverId:p.receiverId,type:p.type??'TEXT',content:p.content,replyToId:p.replyToId,attachments:{create:p.attachments}},include});await tx.conversation.update({where:{id:p.conversationId},data:{updatedAt:new Date()}});return message;});},
 async page(conversationId:string,userId:string,cursor?:string,limit=30){await conversations.assertMember(conversationId,userId);const rows=await prisma.message.findMany({where:{conversationId},include,orderBy:{createdAt:'desc'},take:limit+1,...(cursor?{cursor:{id:cursor},skip:1}:{})});const next=rows.length>limit?rows.pop()!.id:null;return {messages:rows, nextCursor:next};},
 async edit(id:string,userId:string,content:string){const m=await prisma.message.findUnique({where:{id}});if(!m||m.senderId!==userId||m.type!=='TEXT'||m.deletedAt)throw new Error('Message cannot be edited');return prisma.message.update({where:{id},data:{content,editedAt:new Date()},include});},
 async remove(id:string,userId:string){const m=await prisma.message.findUnique({where:{id}});if(!m||m.senderId!==userId)throw new Error('Message cannot be deleted');return prisma.message.update({where:{id},data:{content:'This message was deleted',deletedAt:new Date(),attachments:{deleteMany:{}}},include});},
 async deliver(id:string,userId:string){const m=await prisma.message.findUniqueOrThrow({where:{id}});if(m.receiverId!==userId)throw new Error('Message delivery denied');return m;},
 async react(id:string,userId:string,emoji:string){if(!['❤️','😂','👍','🔥','😮','😢'].includes(emoji))throw new Error('Unsupported reaction');const m=await prisma.message.findUniqueOrThrow({where:{id}});await conversations.assertMember(m.conversationId,userId);const key={messageId_userId_emoji:{messageId:id,userId,emoji}};const existing=await prisma.messageReaction.findUnique({where:key});if(existing)await prisma.messageReaction.delete({where:{id:existing.id}});else await prisma.messageReaction.create({data:{messageId:id,userId,emoji}});return prisma.message.findUniqueOrThrow({where:{id},include});},
 async markRead(conversationId:string,userId:string){const unread=await prisma.message.findMany({where:{conversationId,receiverId:userId,deletedAt:null},select:{id:true,senderId:true}});await prisma.$transaction(unread.map(m=>prisma.messageRead.upsert({where:{messageId_userId:{messageId:m.id,userId}},create:{messageId:m.id,userId},update:{readAt:new Date()}})));return unread;}
};
